---
- name: "Demonstrate connecting to switches"
  hosts: all
  gather_facts: no
  connection: ansible.netcommon.network_cli
  
  tasks:
    ###
    # Collect data
    #
   - name: Run cli_command on Cisco IOS
        ansible.netcommon.cli_command:
          command: show ip int br
        register: result
