---
- name: command testing
  hosts: all
  gather_facts: no
  connection: network_cli

  tasks:

 # Get CLI raw text output for a given command
   ios_command:
       commands:
        - show running-config
...
