---
- name: show version
  hosts: all
  gather_facts: false
  tasks:
    - name: Run command on remote device
      cisco.nxos.nxos_command:
        commands: show version
      register: results
    - name: Show results
      debug:
        msg: "{{ results.stdout_lines }}"
...
