---

- name: Network Getting Started First Playbook
  connection: ansible.netcommon.network_cli
  gather_facts: false
  hosts: all
  tasks:
   cisco.nxos.nxos_command:
    commands: show version   
...
