---
- name: SHOW RUNNING-CONFIG
  hosts: all
  gather_facts: false
  collections:
- ansible.netcommon
- cisco.iosxr

  tasks:
  - name: EXECUTANDO...
    ios_command:
       commands:
        - show running-config
...
