---

- name: SHOW RUNNING-CONFIG
  hosts: all
  gather_facts: false
  tasks:
  - name: EXECUTANDO...
    ios_command:
       commands:
        - show running-config
       register: ls

   - name: Print local
      debug:
        var: ls
...
