---
- name: show version
  hosts: all
  gather_facts: false
  tasks:
    - name: show version
      cisco.nxos.nxos_command:
        commands: show version
      register: output
    -  debug: var=output.stdout_lines
...
